name: vkurse_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.10
  mask_text_input_formatter: ^2.4.0
  flutter_easyloading: ^3.0.5
  http: ^0.13.5
  validators: ^3.0.0
  pin_code_fields: ^7.4.0

  intl_phone_field: ^3.1.0
  
  flutter_map: ^3.1.0
  flutter_latlong: ^1.0.3

  latlng: ^0.2.0
  
  flutter_typeahead: ^4.3.1

  libphonenumber_plugin: ^0.2.5
  equatable: ^2.0.5
  collection: ^1.16.0
  flutter_map_location_marker: ^5.2.1

  yandex_mapkit: ^3.2.0
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/flags/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Thin.ttf
